### ISSUE TITLE
enhancement request: set active/deactive time window

### ISSUE THREAD

**Issue by clach04** [Spitemare/pebble-connection-vibes#2]
The connection_vibes_enable_health() call is great, would you consider adding support for start/stop time for vibs? E.g. don't vibrate after 11pm and resume again at 6am? The caller to pebble-connection-vibes could implement this and call connection_vibes_set_state(ConnectionVibesStateNone) but it would be nice if this library took care of that.

Possible API examples:

```
connection_vibes_set_active_window(6, 23);  // hours
connection_vibes_set_active_window(600, 2300);  // hours and mins as integer
connection_vibes_set_active_window(630, 2355);  // hours and mins as integer, 6:30 am and 11:55pm
```

**Comment by dmorgan81** [comment]
This is a good idea. There's been some chatter about quiet time support coming in the official SDK. No word on when, though. If that takes too long I'll consider going this route.

**Comment by dmorgan81** [comment]
Pebble SDK 4.3 now has `quiet_time_is_active()` which version 1.1.0 now uses.

On aplite this call always returns false (it's actually a #define for false) so there could be value in providing a custom quiet time window on that platform. I have opened #3 to track that work.
